// src/components/shared/Hero/Hero.tsx
import { motion } from "framer-motion";
import s from "./Hero.module.css";
import { easeOutExpo } from "@/utils/transitions";

interface HeroProps {
  title: string;
  subtext: string;
}

export function Hero(props: HeroProps) {
  const { title, subtext } = props;
  return (
    <section className={s.hero}>
      <motion.p
        initial={{ opacity: 0, y: 100 }}
        animate={{ opacity: 1, y: 0 }}
        exit={{ opacity: 0, y: 100 }}
        transition={{
          ease: easeOutExpo,
          delay: 0.7,
          duration: 0.3,
        }}
      >
        {subtext}
      </motion.p>
      <motion.h1
        initial={{ opacity: 0, y: 100 }}
        animate={{ opacity: 1, y: 0 }}
        exit={{ opacity: 0, y: 100 }}
        transition={{
          ease: easeOutExpo,
          delay: .8,
          duration: 0.3,
        }}
      >
        {title}
      </motion.h1>
    </section>
  );
}

// src/lib/components/shared/Hero/Hero.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import './Hero.css';
	import { gsap } from 'gsap';

	interface HeroProps {
		title: string;
		description: string;
	}

	const { title, description }: HeroProps = $props();

	onMount(() => {
		gsap.from('.hero__subtitle, .hero__title', {
			opacity: 0,
			y: 30,
			stagger: 0.15,
			duration: 1,
			ease: 'expo.out',
			delay: .2,
		});
	});
</script>

<section class="hero">
	<span class="hero__subtitle">{description}</span>
	<h1 class="hero__title">{title}</h1>
</section>
