// src/components/features/layout/Footer/Footer.tsx
import { Github, Instagram, Linkedin } from "@/components/icons";
import s from "./Footer.module.css";
import cn from "clsx";
import { Divider } from "@/components/shared/Divider/Divider";
import Button from "@/components/shared/Button/Button";

export function Footer() {
  return (
    <footer className={s["footer"]}>
      <div className="container">
        <p className={s["title"]}>Let's Work Togheter</p>
        <div className={s["main-content"]}>
          <ul className={s["contact-list"]}>
            <li className={s["list-title"]}>Contact me</li>
            <li>
              <a href="mailto:justinlung77@gmail.com">justinlung77@gmail.com</a>
            </li>
            <li>
              <a href="tel:+31646021197">+31646021197</a>
            </li>
          </ul>
          <ul className={s["social-list"]}>
            <li>
              <a href="" target="_blank" rel="noopener noreferrer">
                <Instagram />
              </a>
            </li>
            <li>
              <a href="" target="_blank" rel="noopener noreferrer">
                <Linkedin />
              </a>
            </li>
            <li>
              <a href="" target="_blank" rel="noopener noreferrer">
                <Github />
              </a>
            </li>
          </ul>
        </div>
        <Divider />
        <div className={s["outer-content"]}>
          <div>
            <p>
              &#169; {new Date().getFullYear()} Justin Lung · All Rights
              Reserved
            </p>
          </div>
          <div>
            <p>Creative Frontend Developer</p>
          </div>
        </div>
      </div>
    </footer>
  );
}

// src/lib/components/features/layout/Footer/Footer.svelte
<script lang="ts">
	import Link from '$components/shared/Link/Link.svelte';
	import { socials } from '$lib/util/links';
	import './Footer.css';
</script>

<footer class="footer">
	<div class="footer__top container">
		<span class="footer__top-title">Let's Work Together</span>
		<div class="footer__top-contact">
			<a href="mailto:justinlung77@gmail.com" class="footer_top-contact-link underline">justinlung77@gmail.com</a>
			<a href="tel:+31646021197" class="footer_top-contact-link underline">+31 6 46021197</a>
		</div>
	</div>
	<div class="footer__bottom container">
		<p>© {new Date().getFullYear()} Justin-Lung. All rights reserved.</p>
		<ul class="footer__bottom-socials">
			{#each socials as social}
				<li>
					<Link href={social.url} underline class="footer__bottom-socials-link underline"
						>{social.name}</Link
					>
				</li>
			{/each}
		</ul>
	</div>
</footer>
