// src/routes/about/+page.svelte
<script lang="ts">
	import MetaTags from '$components/features/MetaTags.svelte';
	import About from '$components/shared/About/About.svelte';
	import CardStack from '$components/shared/CardStack/CardStack.svelte';
	import Carousel from '$components/shared/Carousel/Carousel.svelte';
</script>

<MetaTags pageTitle="About" currentUrl="/about" pageDescription="This is the about page" />
<About />
<CardStack />

// src/pages/about.tsx
import MetaTags from "@/components/features/MetaTags";
import { About } from "@/components/shared/About/About";
import { PreFooter } from "@/components/shared/PreFooter/PreFooter";
import { nextClient } from "@lib/client";
import { AboutPageQuery, AboutRecord } from "@lib/generated/sdk";
import { GetStaticProps } from "next";

interface PageProps {
  data: AboutRecord;
}

export default function Page({ data }: PageProps) {
  return (
    <>
      <MetaTags
        pageTitle={"Portfolio - About"}
        pageDescription={"About me"}
        currentUrl={"/about"}
      />
      <About data={data} />
    </>
  );
}

export const getStaticProps: GetStaticProps = async (context) => {
  const [aboutPage] = await Promise.allSettled([nextClient.AboutPage()]);

  return {
    props: {
      data: (aboutPage as PromiseFulfilledResult<AboutPageQuery>).value.about,
    },
  };
};
